version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2
  slack: circleci/slack@3.4.2

workflows:
  my-workflow:
    jobs:
      - slack-notification

jobs:

  slack-notification:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: exit 0
      - slack/status

  build:
    docker:
      - image: circleci/ruby:2.7.1-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: ruby -v
          command: ruby -v
